ramenapp/urls.py
from django.urls import path, include
from . import views

app_name = 'ramenapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    path('post_detail/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('post_update/<int:pk>', views.PostUpdate.as_view(), name='post_update'),
    path('post_delete/<int:pk>', views.PostDelete.as_view(), name='post_delete'),
    path('post_list', views.PostList.as_view(), name='post_list'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('signup', views.SignUp.as_view(), name='signup'),
    path('like/<int:post_id>', views.Like_add, name='like_add'),
    path('like_list', views.LikeDetail.as_view(), name='like_list'),
    path('category_list', views.CategoryList.as_view(), name='category_list'),
    path('category_detail/<str:name_en>',
         views.CategoryDetail.as_view(), name='category_detail'),
    path('search', views.Search, name='search'),
    path('contact_form', views.ContactFormView.as_view(), name='contact_form'),
    path('comment_form/<int:pk>',
         views.CommentFormView.as_view(), name='comment_form'),
    path('comment_delete/<int:pk>',
         views.CommentDelete.as_view(), name='comment_delete'),
    path('reply_form/<int:pk>', views.ReplyFormView.as_view(), name='reply_form'),
#     path('comment/<int:comment_id>/reply_form/<int:pk>', views.ReplyToReplyFormView.as_view(), name='reply_form'),
    path('reply_delete/<int:pk>', views.ReplyDelete.as_view(), name='reply_delete'),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('google285b2115e8e0c8a6.html', views.google, name='google'),
    path('ping', views.ping),
]

ramenproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from .sitemaps import (
    BlogPostSitemap,
    StaticViewSitemap,
)

sitemaps = {
    'blog': BlogPostSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ramenapp.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ramenapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
# from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.core.mail import send_mail


class Author(models.Model):
    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=50)
    name_en = models.CharField('カテゴリ名英語', max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def post_count(self):
        n = Post.objects.filter(category=self).count()
        return n

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    title = models.CharField('タイトル', max_length=100)
    content = models.TextField('内容')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    star = models.IntegerField('評価', blank=False, default=3, validators=[
                               MaxValueValidator(5), MinValueValidator(1)])
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_num = models.IntegerField(default=0)

    def like_count(self):
        n = Like.objects.filter(post=self).count()
        return n

    def __str__(self):
        return self.title


class Like(models.Model):
    post = models.ForeignKey(Post, verbose_name="投稿", on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, verbose_name="Likeしたユーザー", on_delete=models.PROTECT)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField('名前', max_length=50, blank=True, null=True)
    text = models.TextField()
    mailadress = models.EmailField('メールアドレス', blank=True, null=True, help_text='(※入力しておくと、返信があった際に通知します。コメント欄には表示されません。登録の際にメールアドレスを登録している場合必要ありません)')
    useremail = models.EmailField('ユーザーのメールアドレス', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.text


class Reply(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name='replies', null=True)
    author = models.CharField('名前', max_length=50, blank=True, null=True)
    authority = models.CharField(max_length=100, blank=True, null=True)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

#     def send_email_notif(self):
#         subject = "【ラーメンブログ】コメント返信"
#         message = "【ラーメンブログ】あなたのコメントに返信が届きました。"
#         from_email = settings.DEFAULT_FROM_EMAIL
#         recipient_list = [settings.EMAIL_HOST_USER]
#         send_email = send_mail(
#             subject, message, from_email, recipient_list)
#         return send_email


# @receiver(post_save, sender=Reply)
# def comment_reply_receiver(sender, instance, created, **kwargs):
#     if created:
#         instance.send_email_notif()


ramenapp/views.py
from django.shortcuts import render, resolve_url, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from .models import Post, Like, Category, Comment, Reply, Author
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import PostForm, LoginForm, SignUpForm, SearchForm, ContactForm, CommentForm, ReplyForm, UserUpdateForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator
from django.core.exceptions import ValidationError
from django.views.generic.edit import FormView
from django.contrib.sitemaps import ping_google
from django.http import JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from .mixins import SuperuserRequiredMixin
from django.contrib.auth.models import User

@login_required
def ping(request):
  try:
    if request.user.is_admin:
      ping_google()  
  except:
    pass
  return redirect('/')


class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        post = Post.objects.get(id=self.kwargs['pk'])
        return post.author == self.request.user

class OnlyMyCommentMixin(UserPassesTestMixin):
    raise_exception=True

    def test_func(self):
        comment=Comment.objects.get(id=self.kwargs['pk'])
        return comment.author==self.request.user

class OnlyMyReplyMixin(UserPassesTestMixin):
    raise_exception=True

    def test_func(self):
        reply=Reply.objects.get(id=self.kwargs['pk'])
        return reply.author==self.request.user

class OnlyYouMixin(UserPassesTestMixin):
    """本人か、スーパーユーザーだけユーザーページアクセスを許可する"""
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

class AuthorCreate(LoginRequiredMixin, CreateView):
    model = Author
    fields = ['name']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class UserDetail(OnlyYouMixin, DetailView):
    """ユーザーの詳細ページ"""
    model = User
    # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く
    template_name = 'ramenapp/user_detail.html'

class UserUpdate(OnlyYouMixin, UpdateView):
    """ユーザー情報更新ページ"""
    model = User
    form_class = UserUpdateForm
    template_name = 'ramenapp/user_form.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く

    def get_success_url(self):
        return resolve_url('ramenapp:user_detail', pk=self.kwargs['pk'])

class Index(TemplateView):
    template_name = 'ramenapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        if Post.updated_at:
            post_list = Post.objects.all().order_by('-updated_at')[:6]
        else:
            post_list = Post.objects.all().order_by('-created_at')[:6]
        context = {
            'post_list': post_list,
        }
        return context


class PostCreate(SuperuserRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('ramenapp:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, '記事を登録しました。')
        return resolve_url('ramenapp:index')


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        detail_data = Post.objects.get(id=self.kwargs['pk'])
        category_posts = Post.objects.filter(
            category=detail_data.category).order_by('-created_at')[:5]
        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }
        return params


class PostUpdate(SuperuserRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request, '記事を更新しました。')
        return resolve_url('ramenapp:post_detail', pk=self.kwargs['pk'])


class PostDelete(SuperuserRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        messages.info(self.request, '記事を削除しました。')
        return resolve_url('ramenapp:index')


class PostList(ListView):
    model = Post
    paginate_by = 5

    def get_queryset(self):
        if Post.updated_at:
            return Post.objects.all().order_by('-updated_at')
        else:
            return Post.objects.all().order_by('-created_at')


class Login(LoginView):
    form_class = LoginForm
    template_name = 'ramenapp/login.html'


class Logout(LogoutView):
    template_name = 'ramenapp/logout.html'


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'ramenapp/signup.html'
    success_url = reverse_lazy('ramenapp:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user, backend='django.contrib.auth.backends.ModelBackend')
        self.object = user
        messages.info(self.request, 'ユーザー登録をしました。')
        return HttpResponseRedirect(self.get_success_url())


@login_required
def Like_add(request, *args, **kwargs):
    post = Post.objects.get(id=kwargs['post_id'])
    is_liked = Like.objects.filter(user=request.user, post=post).count()
    if is_liked > 0:
        liking = Like.objects.get(
            post_id=kwargs['post_id'], user=request.user)
        liking.delete()
        post.like_num -= 1
        # post.save()
        messages.info(request, 'お気に入りを削除しました。')
        return redirect('ramenapp:index')
    post.like_num += 1
    # post.save()
    like = Like()
    like.user = request.user
    like.post = post
    like.save()

    messages.success(request, 'お気に入りに追加しました。')
    return redirect('ramenapp:index')

class CategoryList(ListView):
    model = Category


class CategoryDetail(DetailView):
    model = Category
    slug_field = 'name_en'
    slug_url_kwarg = 'name_en'

    def get_context_data(self, *args, **kwargs):
        detail_data = Category.objects.get(name_en=self.kwargs['name_en'])
        category_posts = Post.objects.filter(
            category=detail_data.id).order_by('-created_at')

        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }

        return params


def Search(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            freeword = searchform.cleaned_data['freeword']
            search_list = Post.objects.filter(
                Q(title__icontains=freeword) | Q(content__icontains=freeword))

        params = {
            'search_list': search_list,
        }

        return render(request, 'ramenapp/search.html', params)


class LikeDetail(ListView):
    model = Like

    paginate_by = 5

    def get_queryset(self):
        return Like.objects.filter(user=self.request.user)


class ContactFormView(FormView):
    template_name = 'ramenapp/contact_form.html'
    form_class = ContactForm

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)

    def get_success_url(self):
        messages.info(self.request, 'お問い合わせは正常に送信されました。')
        return resolve_url('ramenapp:index')


class CommentFormView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        post = get_object_or_404(Post, pk=post_pk)
        # form.instance.author = self.request.user
        # form.instance.author_id = self.request.user.id
        comment.useremail = self.request.user.email
        comment.post = post
        comment.request = self.request
        comment.save()
        return redirect('ramenapp:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        # post = get_object_or_404(Post, pk=post_pk)
        # context = {
        #     'post': post
        # }
        context['post'] = get_object_or_404(Post, pk=post_pk)
        context['form'] = CommentForm(initial = { 
                'author': self.request.user, 
                'mailadress' : self.request.user.email,
            }) 
        return context

# def comment_initail(request):
#     queryset = User.objects.get(id=request.user.id)
   
#     initial_data = {
#         'author': queryset.username,
#     }
 
#     form = CommentForm(
#         initial=initial_data
#     )
 
#     context = {
#         'form': form
#     }
#     return render(request, 'ramenapp/comment_form.html', context)
# @login_required
# def comment_remove(request, pk):
#     comment = get_object_or_404(Comment, pk=pk)
#     comment.delete()
#     return redirect('ramenapp;post_detail', pk=comment.post.pk)
class CommentDelete(OnlyMyCommentMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        comment = get_object_or_404(Comment, pk=self.kwargs['pk'])
        pk = comment.post.id
        messages.info(self.request, 'コメントを削除しました。')
        return resolve_url('ramenapp:post_detail', pk=pk)


class ReplyFormView(LoginRequiredMixin, CreateView):
    model = Reply
    form_class = ReplyForm

    def form_valid(self, form):
        reply = form.save(commit=False)

ramenapp/templates/ramenapp/comment_confirm_delete.html
{% extends 'ramenapp/base.html' %}


{% block content %}
<div class="row">
    <div class="col-md-9">
        <br>
        <h2>削除</h2>
        <br>
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p>以下の内容を本当に削除しますか？</p>
                <input type="submit" class="btn btn-outline-danger" value="削除する">
                <button type="button" onclick="history.back()"
                    class="btn ml-5 btn-outline-primary waves-effect">戻る</button>
            </form>
        </div>
        <br>
        <hr>
        <p>コメント内容</p>
        {{object.text}}
    </div>
</div>
{% endblock content %}

ramenapp/templates/ramenapp/comments.html
{% if object.comments %}
    <div class="comments">
        {% for comment in object.comments.all %}
        <div class="comment">
            <strong>{{ comment.author }}</strong>・{{ comment.created_at }}
            <p>{{ comment.text|linebreaksbr }}</p>
            <p>
                {% if request.user.is_authenticated%}
                <a href="{% url 'ramenapp:reply_form' comment.pk %}">返信する</a>
                {% endif %}
                {% if comment.useremail == request.user.email %}
                <a class="text-danger" href="{% url 'ramenapp:comment_delete' comment.pk %}">削除</a>
                {% endif %}
            </p>
            {% for reply in comment.replies.all %}
                <div class="reply ml-5">
                    <strong>{{ reply.author }}</strong>・{{ reply.created_at }}{{reply.authority}}
                    <p>{{ reply.text|linebreaksbr }}</p>
                    <p>
                        {% if reply.authority == request.user.email %}
                            <a class="text-danger" href="{% url 'ramenapp:reply_delete' reply.pk %}">削除</a>
                        {% endif %}
                    </p>
                </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
{% endif %}

ramenapp/templates/ramenapp/contact_form.html
{% extends 'ramenapp/base.html' %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <br>
            <br>
            <h1>お問い合わせ</h1>
            <br>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">送信</button>
            </form>
            <br>
        </div>
    </div>
</div>
{% endblock content %}

ramenapp/templates/ramenapp/google285b2115e8e0c8a6.html
google-site-verification: google285b2115e8e0c8a6.html

ramenapp/templates/ramenapp/index.html
{% extends 'ramenapp/base.html' %}


{% block content %}
<!-- Start your project here-->
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h2 class="display-4 text-center">{{request.site.siteconfig.top_title}}</h2>
    <p class="lead text-center">{{request.site.siteconfig.top_subtitle}}</p>
  </div>
</div>
<!-- /Start your project here-->
<br><br>
<div class="row">
  <!-- Card deck -->
  <div class="card-deck">

    <!-- Card -->
    <br><br>
    {% for item in post_list %}
    <div class="col-md-4">
      <div class="card mb-4 card-content">

        <!--Card image-->
        <div class="view overlay">
          {% if item.thumbnail %}
          <img class="card-img-top" src="{{ item.thumbnail.url }}" alt="{{item.title}}">
          {% else %}
          <img class="card-img-top" src="media/images/hari-panicker-2t28IxSTqF4-unsplash-min.jpg" alt="Card image cap">
          {% endif %}
          <a href="{% url 'ramenapp:post_detail' item.id %}">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!--Card content-->
        <div class="card-body">

          <!--Title-->
          <h4 class="card-title"><a class="main-title" href="{% url 'ramenapp:post_detail' item.id %}" style="color: black;">{{item.title}}</a>&nbsp;&nbsp;<i class="fas fa-star"
              style="color: yellow;"></i><small>{{item.star}}</small></h4>
          <p>{{ item.category }}</p>
          <!--Text-->
          <p class="card-text">{{item.content|safe|truncatechars_html:50}}</p>
          <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
          <a href="{% url 'ramenapp:post_detail' item.id %}" type="button" class="btn btn-light-blue btn-md">内容を見る</a>
          <a href="{% url 'ramenapp:like_add' item.pk %}"><i class="fas fa-heart"
              style="color: pink;"></i></a>&nbsp;{{item.like_count}}
        </div>
        <!-- Card footer -->
        <div class="card-footer text-muted text-center">
          <small>更新日: 
            {% if item.updated_at %}
            {{item.updated_at.date}}
            {% else %}
            {{item.created_at.date}}
            {% endif %}
          </small>
        </div>

      </div>

      <!-- Card -->
    </div>
    {% endfor %}


  </div>

  <!-- Card deck -->



</div>
<br><br>
<div class="button">
  <a href="{% url 'ramenapp:post_list' %}"><button type="button"
      class="btn btn-outline-default waves-effect">全ての記事を見る</button></a>
</div>
<br>
{% endblock content %}

ramenapp/templates/ramenapp/logout.html
{% extends 'ramenapp/base.html' %}


{% block content %}
<div class="row">
    <div class="col-md-6">
        <br>
        <h2>ログアウト</h2>
        <br>
        <p>ログアウトしました。</p>
    </div>
</div>
{% endblock content %}
    

ramenapp/templates/ramenapp/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; 最初へ</a>
        <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">次へ</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">最後へ &raquo;</a>
        {% endif %}
    </span>
</div>

ramenapp/templates/ramenapp/post_confirm_delete.html
{% extends 'ramenapp/base.html' %}


{% block content %}
<div class="row">
    <div class="col-md-9">
        <br>
        <h2>削除</h2>
        <br>
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p>以下の内容を本当に削除しますか？</p>
                <input type="submit" class="btn btn-outline-danger" value="削除する">
            </form>
        </div>
        <br>
        <p>タイトル</p>
        {{object.title}}
        <hr>
        <p>内容</p>
        {{object.title}}
    </div>
</div>
{% endblock content %}
    

ramenapp/templates/ramenapp/post_form.html
{% extends 'ramenapp/base.html' %}


{% block content %}
<div class="row">
    <div class="col-md-9">
        <br>
        <h2>登録・更新</h2>
        <br>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label>タイトル</label>
                {{form.title}}
            </div>
            <div class="form-group">
                <label>カテゴリー</label>
                {{form.category}}
            </div>
            <div class="form-group">
                <label>評価</label>
                {{form.star}}
                <p style="color: red;">※1~5でお願いします。</p>
            </div>
            <div class="form-group">
                <label>サムネイル画像</label>
                {{form.thumbnail}}
            </div>
            <br>
            <div class="form-group">
                <label>内容</label>
                {{form.content}}
            </div>
            <br>
            <button type="submit" class="btn btn-primary">保存</button>
        </form>
    </div>
</div>
{% endblock content %}

ramenapp/templates/ramenapp/reply_form.html
{% extends 'ramenapp/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <br>
            <br>
            <h1 class="mb-4">コメント返信フォーム</h1>
            {% if reply %}
            <strong>To: {{ reply.author }}</strong>
            {% else %}
            <strong>To: {{ comment.author }}</strong>
            {% endif %}
            <p class="text-black-50">{{ comment.text|linebreaksbr }}</p>
            <form method="POST">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">送信</button>
            </form>
            <br>
        </div>
    </div>
</div>
{% endblock content %}

ramenapp/templates/ramenapp/search.html
{% extends 'ramenapp/base.html' %}


{% block content %}
<div class="row">
    <div class="col-md-9">
        <br>
        <h2>検索結果</h2>
        <br>
        <table class="table">
            <thead>
                <tr>
                    <th width="200px">タイトル</th>
                    <th>内容</th>
                    <th width="200px">更新日時</th>
                <tr>
            </thead>
            <tbody>
                {% for item in search_list %}
                <tr>
                    <td><a class="serch-title" style="color: blue;" href="{% url 'ramenapp:post_detail' item.pk %}">{{item.title}}</a></td>
                    <td>{{item.content|safe|truncatechars_html:50}}</td>
                    {% if updated_at %}
                    <td>{{item.updated_at.date}}</td>
                    {% else %}
                    <td>{{item.created_at.date}}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        {% include 'ramenapp/pagination.html' %}
        <br>
    </div>
</div>
{% endblock content %}

ramenapp/templates/ramenapp/signup.html
{% extends 'ramenapp/base.html' %}


{% block content %}
<div class="row">
    <div class="col-md-6">
        <br><br>
        <h2>サインアップ</h2>
        <br>
        <p style="color: red;">※ユーザー名はアカウントから変更可能です！</p>
        <br>
        <a class="btn btn-danger btn-block" href="{% url 'social:begin' 'google-oauth2' %}"><i
                class="fab fa-google mr-3 fa-2x"></i>Googleでユーザー登録</a>
        <br><br>
        <a href="{% url 'social:begin' 'github' %}" class="btn btn-block btn-black"><i
                class="fab fa-github mr-3 fa-2x"></i>GitHubでユーザー登録</a>
        <br><br>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            {{field.label}}
            {{ field }}
            {{ field.errors }}
            <br>
            {% endfor %}
            <button type="submit" class="btn btn-primary">サインアップ</button>
        </form>
    </div>
</div>
{% endblock content %}

ramenapp/templates/ramenapp/user_detail.html
{% extends "ramenapp/base.html" %}
{% block content %}
<br>
<br>
<table class="table">
  <tbody>
    <tr>
      <th>メールアドレス</th>
      <td>{{ user.email }}</td>
    </tr>
    <tr>
      <th>名前</th>
      <td>{{ user.username }}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

ramenapp/templates/ramenapp/user_form.html
{% extends "ramenapp/base.html" %}
{% block content %}
<br>
<br>
<br>
<form action="" method="POST">
  {{ form.as_p }}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-lg">送信</button>
</form>
{% endblock %}